# In aci_v2/mces_mvp/models.py
# Date: June 3, 2025
# Author: Lily AI for The Architect (ACI v2.0 Project)

from typing import TypedDict


class MacroActionStepMVP(TypedDict):
    step_id: str  # Unique within the macro, e.g., "step_1", "step_2"
    parameters: dict[
        str, str
    ]  # For "SEND_TO_LILY", this must contain {"message_text": "Actual command for Lily"}


class MacroDefinitionMVP(TypedDict):
    macro_id: str  # Unique UUID for the macro, generated by MCES
    last_modified_timestamp_utc: str  # ISO 8601 format
    last_modified_timestamp_utc: str  # ISO 8601 format
